### PR TITLE
made it compatable with py3 added feature to run against file 

### PR DESCRIPTION
**Pull request by sair770**
fixes issues 14,1

### CODE REVIEW

**Comment by UltimateHackers** [comment]
```
d3v@blazy:~/Decodify# python dcode -rot all sasa

    __                         __      
  |/  |                   | / /        
  |   | ___  ___  ___  ___|  (         
  |   )|___)|    |   )|   )| |___ \   )
  |__/ |__  |__  |__/ |__/ | |     \_/ 
                                    /  
usage: dcode [-h] [-s] [-rev] [-rot] [-file] string
dcode: error: unrecognized arguments: sasa
```
Tried with both `python 2` and `python 3`. `-rev` option throws the same error as well.

**Comment by MrJoiny** [comment]
The problem is the action in the -rot argument.
Remove the `action="store_true"` in the -rot argument line.

Here is a link for all actions.
https://docs.python.org/3/library/argparse.html#action

Why did you use -1 in 
`listofstrings = f.read().replace('\r','').split('\n')[:-1]`
it skips the last line.

for the quit problem using quit() works.
But since you added file Support you could do something like that: 
```
def Quit():
    global currentstring
    if listlenght == currentstring:
        quit()
    else:
        print("String number: ", currentstring)
        currentstring += 1
        decode(listofstrings[currentstring-1], '')
```

**Comment by sair770** [comment]
Hey,
Actually I have done this to remove the extra empty string get when you split the last '\n' I will add an if condition to mitigate that.Thanks for the feedback

**Comment by sair770** [comment]
Done the required changes

**Comment by MrJoiny** [comment]
Good work there, but you need to call `global currentstring` in the files function to apply `currentstring = 1`
Otherwise it decodes the first string two times.

**Comment by sair770** [comment]
Done
`

**Comment by UltimateHackers** [comment]
Hi there!
First of all sorry for such a late response. I know it sucks but I was busy in my exams.
Thanks for fixing such a major issue but I would like to mention two things that are bothering me.
1. Why the `file` argument is `store_true`? It should be used to specify location of a file containing strings to be decoded. I don't know why you want to use it as a boolean value specifier.
2. Can you please remove the `Decoding :  NjM3YTQyNzQ1YTQ0NGUzMg==` thingy?
Thanks again.

PS: This time the response time will be lesser than 6 hours.

**Comment by sair770** [comment]
> Why the file argument is store_true? It should be used to specify location of a file containing strings to be decoded. I don't know why you want to use it as a boolean value specifier.

 looks like the args.string is mandatory. So, if i use the args.files to store the path to file then the strings part throws an error, I tried what you mentioned and it was throwing errors.

> Can you please remove the Decoding : NjM3YTQyNzQ1YTQ0NGUzMg== thingy?
I can but it would make it difficult to identify which string is being decoded, dont you think so?

**Pull request merged**
