### PR TITLE
replaced setup.sh with a makefile

### PR DESCRIPTION
**Pull request by tommaswitvrouwen**
Replaced setup.sh with a makefile for an easier install and uninstall.  
to install:  
`make install`

to uninstall:  
`make uninstall`

### CODE REVIEW

**Comment by lodi-g** [comment]
Imho, you should use a DESTDIR variable so any user can customize the installation directory.
It'd also make it easier for package maintainers.

Thanks!

**Comment by tommaswitvrouwen** [comment]
Good call! It's been added and it will default to '/usr/local/bin' when not specified

**Comment by UltimateHackers** [comment]
Thanks for contributing to the project, I really appreciate it.

**Comment by tommaswitvrouwen** [comment]
I was unaware of that of that. Should I open another pull request for this change?

**Pull request merged**
